Pipfile
mbed_build/_internal/cmake_renderer.py
mbed_build/_internal/templates/CMakeLists.tmpl
news/20200325.feature
setup.py
tests/test_cmake_renderer.py

Add initial functionality for rendering and outputting a top-level CMakeLists.txt file. 
In the spirit of small PRs I have kept this very simple to start will but it will change over the next PRs.

✨ Cmake templates

---

mbed_build/_internal/find_files.py
mbed_build/_internal/mbed_lib.py
news/20200402.feature
tests/_internal/test_find_files.py
tests/_internal/test_mbed_lib.py

Filter list of `mbed_lib.json` files using target labelling rules.
- An example of labelled path is `/path/FEATURE_FOO/mbed_lib.json`, where label type is "FEATURE" and label value is "FOO".
- If a path contains label values that are not allowed for a given target, it should be filtered out.
- There's many label types "TOOLCHAIN", "FEATURE", "TARGET" to name a few - this PR only covers target labels: "TARGET", "FEATURE", "COMPONENT"
Given a label "FEATURE_FOO"
`/path/FEATURE_FOO/somefile.txt` ✅
`/path/FEATURE_BAZ/somefile.txt` ❌
`/path/FEATURE_FOO/FEATURE_BAR/somefile.txt` ❌
- while performing some e2e tests vs existing tools I've discovered that `.mbedginore` does not work correctly, so fixing a bug as well

✨ mbed_lib.json discovery (part 2)

---

mbed_build/_internal/mbed_lib.py
news/20200406.feature
tests/_internal/test_mbed_lib.py

Ignore legacy hardcoded directories from old tools when finding `mbed_lib.json` files.
Full list available here: https://github.com/ARMmbed/mbed-os/blob/master/tools/resources/__init__.py#L50
- running find did not yield any mbed_lib.json files in anything other than TESTS
- I'm including TEST_APPS only because it's the only other directory from this list that exists in mbed-os codebase
- FWIW KL25Z exists under TESTS/

✨ Add temporary fix for legacy directories from old tools

---

mbed_build/_internal/mbed_tools/export.py
mbed_build/mbed_build.py
news/20200408.bugfix
tests/_internal/mbed_tools/test_export.py
tests/test_mbed_build.py

mbed-project accesses the targets.json file via project dir not mbed os dir.

🐛Correct path name

---

mbed_build/_internal/mbed_tools/export.py
news/20200408.misc
tests/_internal/mbed_tools/test_export.py

By default use cwd as project path in export command

♻️Default project path

---

mbed_build/_internal/cmake_file.py
mbed_build/_internal/mbed_tools/export.py
news/2020040801.misc
tests/_internal/mbed_tools/test_export.py

Print a message after successful generation of files to give the user more feedback.

✨Add user feedback

---

mbed_build/_internal/find_files.py
mbed_build/mbed_build.py
news/20200414.major
tests/_internal/test_find_files.py
tests/test_mbed_build.py

Update code to work with the new naming in mbed-targets.
The tests will fail in the CI until the changes have been released in mbed-targets, but putting this up as a PR anyway so we can see the effect of the renaming.

♻️Update targets

---

mbed_build/_internal/config/config.py
mbed_build/_internal/config/config_modifiers.py
news/20200415.misc
tests/_internal/config/factories.py
tests/_internal/config/test_config.py
tests/_internal/config/test_config_layer.py
tests/_internal/config/test_config_modifiers.py

1. Turns out that w/o `__init__.py` mypy does not care about your types - adding missing file.
2. Split config assembly integration test into two separate ones - one dealing with simplest case, other with target overrides.
3. Use `TypedDict` instead of `dataclass`. Rationale is that I'm mutating state anyway (😨) so why not treat the entire configuration object as a dict - the dot access vs dict key distinction is a tad confusing.
4. Make mutation more explicit.

♻️ Configuration assembly fixes

---

mbed_build/_internal/config/config_modifiers/build_modifiers.py
mbed_build/_internal/config/config_modifiers/set_target_attribute.py
news/20200417.feature
tests/_internal/config/config_modifiers/test_build_modifiers.py
tests/_internal/config/config_modifiers/test_set_target_attribute.py
tests/_internal/config/test_config.py

When a cumulative target override has no `_add` or `_remove` suffix, the cumulative value should be overwritten with new contents.

✨ Handle strict cumulative overrides

---

mbed_build/_internal/config/config.py
mbed_build/_internal/config/config_layer.py
mbed_build/_internal/config/config_source.py
news/20200420.feature
tests/_internal/config/factories.py
tests/_internal/config/test_config.py
tests/_internal/config/test_config_layer.py
tests/_internal/config/test_config_source.py

To avoid configuration clashes, namespacing is required. This is an attempt to replicate namespacing rules from old tools to make this whole shenanigan work.
What I've managed to decipher:
1. `targets.json`
```
"config": {
"foo": {...}  # becomes "target.foo": {...}
}
```
will be equivalent to `ConfigSource(namespace="target")` in new code
2. `mbed_lib.json`
```
"name": "lib_name",
"config": {
"foo": {...} # becomes "lib_name.foo"
}
"target_overrides": {
"*": {
"target.foo": {...} # remains "target.foo"
"foo": {...} # becomes "lib_name.foo"
}
}
```
will be equivalent to`ConfigSource(namespace="lib_name")` in new code
3. `mbed_app.json` 
```
"config": {
"foo": {...} # becomes "app.foo"
}
"target_overrides": {
"*": {
"target.foo": {...} # remains "target.foo"
"some-prefix.foo": {...} # …
```

✨ Configuration assembly namespaces

---

mbed_build/_internal/config/config.py
news/20200424.feature
tests/_internal/config/test_config.py

Turns out not all of the configuration options have a "macro_name" property.
Looking at old tools code explains that it is autogenerated for those:
https://github.com/ARMmbed/mbed-os/blob/64853b354fa188bfe8dbd51e78771213c7ed37f7/tools/config/__init__.py#L129

✨ Generate Option macro name if missing

---

mbed_build/_internal/config/assemble_build_config.py
mbed_build/_internal/config/config.py
mbed_build/_internal/config/cumulative_data.py
mbed_build/_internal/config/source.py
news/20200427.feature
tests/_internal/config/factories.py
tests/_internal/config/test_assemble_build_config.py
tests/_internal/config/test_config.py
tests/_internal/config/test_cumulative_data.py
tests/_internal/config/test_source.py

Turns out macros are not macros. 😑 
Macros used in configuration come from yet another config property called "macros".
---
I've been looking at the current configuration generation code and it does not seem to use macros defined standalone in targets.json. FWIW there's three ways of defining macros:
1) via "config" section - each config option has a macro - all *.json files
2) via "macros" cumulative attribute under "overrides" ("macros,macros_add,macros_remove") - only targets.json file
3) via "macros" attribute sibling to "config" and "target_overrides" - only mbed_lib.json and mbed_app.json
**The 2) does not seem to be used at all.**
Relevant piece of code: https://github.com/ARMmbed/mbed-os/blob/64853b354fa188bfe8dbd51e78771213c7ed37f7/tools/config/__init__.py#L1261
Note, that …

✨ Configuration assembly macros

---

mbed_build/__main__.py
mbed_build/_internal/mbed_tools/config.py
mbed_build/mbed_tools.py
news/20200428.feature
setup.py
tests/_internal/config/factories.py
tests/_internal/mbed_tools/test_config_command.py
tests/test_mbed_tools.py

Add config command. It prints configuration settings in three formats - tabular, json and legacy (legacy should only be used for checking output against our test archive).
I haven't pulled out any shared code into mbed-tools-libs since there was no particular overlapping logic with mbed-devices. The way to keep consistent is just to make sure we use `tabulate` for tables in both places in the same mode. Still unsure if that is worth abstracting in some way. What do you think? We use the same libraries across packages elsewhere and don't abstract them.

✨Config command

---

news/20200428.misc
setup.py

So that we can make future breaking changes to Mbed packages relied on by mbed-tools, a version specifier is set for each Mbed package. This simplifies development, allowing internal interfaces to be changed while ensuring that new tools will not be installed if the are not compatible.

📌Add a version specifier to the dependencies for Mbed packages

---

mbed_build/_internal/config/config.py
mbed_build/_internal/config/cumulative_data.py
mbed_build/_internal/config/source.py
news/2020042801.misc
tests/_internal/config/factories.py
tests/_internal/config/test_assemble_build_config.py
tests/_internal/config/test_config.py
tests/_internal/config/test_cumulative_data.py
tests/_internal/config/test_source.py

Sources should know as little as possible.
Previously, upon building a Source it'd look into what `cumulative_data.CUMULATIVE_OVERRIDE` is and group the parsed data accordingly. `CumulativeData` would then parse the source, knowing where to look for it. 
While working on _bootloader overrides_, I decided this is not that great and should happen where the data is parsed instead of where it's read.
The side effect of that is that `Config` parsing will now need to know to ignore certain keys. While not great either, I think it's clearer and makes for more transparent `Source`s.
---
As I branched of my previous work, I'm targeting `configuration-assembly-app-layer` for the sake of smaller diff. Once `mbed-targets` is merged and I can close https://github.com/ARMmbed/mbed-build/pull/35, I will …

♻️ Configuration assembly refactor sources

---

mbed_build/_internal/config/bootloader_overrides.py
mbed_build/_internal/config/config.py
mbed_build/_internal/config/cumulative_data.py
news/20200429.feature
tests/_internal/config/test_bootloader_overrides.py
tests/_internal/config/test_config.py

Ability to parse bootloader overrides. This step is necessary to complete configuration parsing.
I'm not 100% sure what they're used for, but they're not part of the config used for header file. 
I've added an ability to gather the information anyway - will be useful at a later stage.

✨Configuration assembly bootloader overrides

---

mbed_build/_internal/config/config.py
mbed_build/_internal/mbed_tools/config.py
news/20200429.bugfix
tests/_internal/config/test_config.py

- Bools are converted to ints in old config - replicating that behaviour.
- I noticed that config command does not show `0` values - it should only hide `None` - fixed.

🐛 Configuration assembly sanitize booleans

---

news/20200702.bugfix
pyproject.toml

SPDX check is failing because it can't find an MIT license...

Fix SPDX check

---

.pre-commit-config.yaml
news/20200707.bugfix

The `assert-news` with option `-l` is designed with an assumption that
there will only be one commit per PR, therefore it expects a newsfile
for every commit which is incorrect. A newsfile is expected per PR.
Therefore removing `assert-news` from pre-commit checks.
CI will still run `assert-news` on every PR and will fail if newsfile is
missing in the PR.
Signed-off-by: Devaraj Ranganna <devaraj.ranganna@arm.com>

Remove `assert-news` from pre-commit checks

---

mbed_build/_internal/templates/mbed_config.tmpl
news/20200708184705.bugfix

`#endif` was missing from the config header template

Fix include guard in config header template

---

mbed_build/_internal/config/source.py
news/20200708205257.bugfix
tests/_internal/config/test_source.py

When JSON decoding fails we just get a fairly useless stack trace.
Log an error message containing the path to the offending JSON file.

Log a more useful error message if JSON decoding fails

---

mbed_build/_internal/templates/mbed_config.tmpl
news/20200720102434.bugfix

Add a default profile to mimic the old tools behaviour.

Add default develop profile to generated cmake config

---

news/20200720153405.bugfix
setup.py

`mbed-targets` was pinned to `1.0` it's now at `1.1`.

Update mbed-targets dependency
